name: Docker

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.github/ISSUE_TEMPLATE/*'
    branches: [ master ]

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
    - uses: actions/checkout@v2

    - name: Build image
      run: docker build --file Dockerfile --tag image --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF=`git rev-parse --short HEAD` .

    - name: Log into docker hub
      run: echo "${{ secrets.docker_hub_token }}" | docker login --username ${{ secrets.docker_hub_username }} --password-stdin

    - name: Push image to registry
      run: |
        docker tag image ducksify/akamai-toolbox
        docker push ducksify/akamai-toolbox:latest
