name: Release

on:
  push:
    tags:
    - '*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Fetch tags/branches history
        run: git fetch --prune --unshallow
      - name: Build wrapper
        run: |
          _TAG=$(echo "${{ github.ref }}" | sed "s|refs/tags/||g")
          sed -i "s|^TAG=\"latest\"|TAG=\"${_TAG}\"|" bin/akamai-toolbox
          cd bin && sha256sum akamai-toolbox > ../akamai-toolbox.sha256
          sed -i 's|bin/akamai-toolbox|akamai-toolbox|' ../akamai-toolbox.sha256
      - shell: bash
        id: changelog
        run: |
          _TAG=$(echo "${{ github.ref }}" | sed "s|refs/tags/||g")
          _PREVIOUS_TAG=$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1))
          _RELEASE_CHANGELOG="$(git log --pretty=format:"%h %s" ${_PREVIOUS_TAG}...${_TAG})"

          # hack from https://github.community/t5/GitHub-Actions/set-output-Truncates-Multiline-Strings/td-p/37870
          _RELEASE_CHANGELOG="${_RELEASE_CHANGELOG//'%'/'%25'}"
          _RELEASE_CHANGELOG="${_RELEASE_CHANGELOG//$'\n'/'%0A'}"
          _RELEASE_CHANGELOG="${_RELEASE_CHANGELOG//$'\r'/'%0D'}"

          echo "::set-output name=RELEASE_CHANGELOG::$_RELEASE_CHANGELOG"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ### Changelog
            ${{ steps.changelog.outputs.RELEASE_CHANGELOG }}
          draft: false
          prerelease: false
      - name: Upload akamai-toolbox to release
        id: upload-release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: bin/akamai-toolbox
          asset_name: akamai-toolbox
          asset_content_type: text/plain
      - name: Upload checksum to release
        id: upload-checksum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: akamai-toolbox.sha256
          asset_name: akamai-toolbox.sha256
          asset_content_type: text/plain

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
